"""
states.py

States are named conditions representing what screen the game is currently showing.

You can add more states as you learn the UI.
"""

STATE_UNKNOWN = "UNKNOWN"
STATE_IN_RUN = "IN_RUN"
STATE_DEAD = "DEAD"
STATE_MENU = "MENU"
STATE_LEAVE_MENU = "LEAVE_MENU"
STATE_AUTO_STOPPED = "AUTO_STOPPED"
STATE_NET_REVEAL = "NET_REVEAL"
STATE_STUCK_IN_LOBBY = "STUCK_IN_LOBBY"
STATE_GAME_CLOSED = "GAME_CLOSED"
STATE_DISCONNECTED = "DISCONNECTED"
STATE_HOME_SCREEN = "HOME_SCREEN"
STATE_FISH_MENU = "FISH_MENU"
STATE_SERVER_MENU = "SERVER_MENU"
STATE_PRIVATE_SERVERS_MENU = "PRIVATE_SERVERS_MENU"
STATE_FISH_MENU_SCROLLED_DOWN = "FISH_MENU_SCROLLED_DOWN"